#!/usr/bin/env bash
# vibeos-agent-egress.sh — compile the per-instance network egress allowlist.
#
# systemd's IPAddressAllow= takes IPs/CIDRs, not hostnames — but AI providers
# sit behind CDNs whose IPs drift, so the allowlist is declared BY HOSTNAME
# (/etc/vibeos/agent-egress.conf, plus optional /etc/vibeos/agent.d/<inst>.egress)
# and resolved here into a systemd drop-in that the agent unit picks up at start.
#
# Runs as vibeos-agent-egress@<instance>.service, ordered BEFORE
# vibeos-agent@<instance>.service (IPAddressAllow= is applied at unit start, so
# the drop-in must exist first). The base unit already sets IPAddressDeny=any +
# IPAddressAllow=localhost; this only ADDS the resolved provider IPs. A hostname
# that fails to resolve simply isn't added — fail-closed (the agent can't reach
# an unresolvable provider, never the reverse).
#
# NOTE: IPAddressAllow is a start-time BPF program; CDN drift DURING a long run
# is not re-applied live (that would need an agent restart). Resolution at start
# covers the run; a restart re-resolves. Documented, not silent.

set -euo pipefail

instance="${1:?usage: vibeos-agent-egress.sh <instance>}"
# Defense in depth: the instance (systemd %i, operator-chosen) lands in file
# paths below. Reject anything but a safe name so a malformed instance can never
# escape agent.d/ or the /run drop-in dir (no '/', hence no path traversal).
case "$instance" in
    '' | *[!A-Za-z0-9._-]*)
        echo "vibeos-agent-egress: invalid instance name '${instance}'" >&2
        exit 1
        ;;
esac

conf=/etc/vibeos/agent-egress.conf
extra="/etc/vibeos/agent.d/${instance}.egress"
dropin_dir="/run/systemd/system/vibeos-agent@${instance}.service.d"
out="${dropin_dir}/50-egress.conf"

# Collect hostnames from the default list + the optional per-instance list.
hosts=()
for f in "$conf" "$extra"; do
    [ -r "$f" ] || continue
    # `|| [ -n "$line" ]`: read exits non-zero at EOF when the last line has
    # no trailing newline — without the guard, an operator-written per-instance
    # file created with `printf 'api.host'` silently LOSES its last (or only)
    # host, quieter than an unresolvable one (which at least leaves a comment).
    while IFS= read -r line || [ -n "$line" ]; do
        line="${line%%#*}"                       # strip comments
        line="${line//[[:space:]]/}"             # strip whitespace
        [ -n "$line" ] || continue
        hosts+=("$line")
    done < "$f"
done

# True (0) for a non-routable address that must NEVER enter the allowlist. A
# public AI provider is never at a loopback / link-local / private / cloud-
# metadata address, so a hostname resolving there (DNS poisoning, rebinding, or a
# CNAME to an internal host) would punch a hole through the default-deny egress
# wall to internal infrastructure — 169.254.169.254 (cloud metadata), RFC1918,
# etc. Dropping these keeps the allowlist "public providers only": it can only
# narrow reachability, never open it to the inside.
is_internal_ip() {
    case "$1" in
        127.*|0.*|255.255.255.255) return 0 ;;                 # loopback / this-host / broadcast
        169.254.*) return 0 ;;                                 # link-local incl. cloud metadata
        10.*|192.168.*) return 0 ;;                            # RFC1918
        172.1[6-9].*|172.2[0-9].*|172.3[0-1].*) return 0 ;;    # RFC1918 172.16/12
        # RFC6598 CGNAT 100.64.0.0/10 — no public provider lives there, but
        # overlay/mesh networks (Tailscale tailnets, some CNIs) DO: a poisoned
        # or CNAMEd hostname landing here would open the wall to an internal
        # overlay peer, the exact class this function exists to close.
        100.6[4-9].*|100.[7-9][0-9].*|100.1[0-1][0-9].*|100.12[0-7].*) return 0 ;;
        ::1|::|::ffff:*) return 0 ;;                            # v6 loopback / unspecified / v4-mapped
        [fF][eE]8*:*|[fF][eE]9*:*|[fF][eE][aAbB]*:*) return 0 ;; # v6 link-local fe80::/10
        [fF][cCdD]*:*) return 0 ;;                              # v6 ULA fc00::/7
    esac
    return 1
}

mkdir -p "$dropin_dir"

{
    echo "# Generated by vibeos-agent-egress.sh for instance '${instance}'."
    echo "# Do not edit — regenerated every start from the hostname allowlist."
    echo "[Service]"
    if [ "${#hosts[@]}" -eq 0 ]; then
        echo "# (no hostnames configured; egress stays deny-any except localhost)"
    fi
    for h in "${hosts[@]}"; do
        # getent ahosts yields both A and AAAA records; dedup per host.
        ips="$(getent ahosts "$h" 2>/dev/null | awk '{print $1}' | sort -u || true)"
        if [ -z "$ips" ]; then
            echo "# ${h}: unresolved at start — not allowed (fail-closed)"
            continue
        fi
        echo "# ${h}"
        while IFS= read -r ip; do
            [ -n "$ip" ] || continue
            if is_internal_ip "$ip"; then
                echo "# ${h}: ${ip} DROPPED (non-routable/internal range — refusing to open the egress wall to the inside)"
                continue
            fi
            echo "IPAddressAllow=${ip}"
        done <<< "$ips"
    done
} > "$out"

# Make systemd aware of the fresh /run drop-in before the agent unit starts.
systemctl daemon-reload

echo "egress allowlist compiled -> $out (${#hosts[@]} hostname(s))" >&2
