#!/usr/bin/env bash
# vibeos-agent-egress.sh — compile the per-instance network egress allowlist.
#
# systemd's IPAddressAllow= takes IPs/CIDRs, not hostnames — but AI providers
# sit behind CDNs whose IPs drift, so the allowlist is declared BY HOSTNAME
# (/etc/vibeos/agent-egress.conf, plus optional /etc/vibeos/agent.d/<inst>.egress)
# and resolved here into a systemd drop-in that the agent unit picks up at start.
#
# Runs as vibeos-agent-egress@<instance>.service, ordered BEFORE
# vibeos-agent@<instance>.service (IPAddressAllow= is applied at unit start, so
# the drop-in must exist first). The base unit already sets IPAddressDeny=any +
# IPAddressAllow=localhost; this only ADDS the resolved provider IPs. A hostname
# that fails to resolve simply isn't added — fail-closed (the agent can't reach
# an unresolvable provider, never the reverse).
#
# NOTE: IPAddressAllow is a start-time BPF program; CDN drift DURING a long run
# is not re-applied live (that would need an agent restart). Resolution at start
# covers the run; a restart re-resolves. Documented, not silent.

set -euo pipefail

instance="${1:?usage: vibeos-agent-egress.sh <instance>}"

conf=/etc/vibeos/agent-egress.conf
extra="/etc/vibeos/agent.d/${instance}.egress"
dropin_dir="/run/systemd/system/vibeos-agent@${instance}.service.d"
out="${dropin_dir}/50-egress.conf"

# Collect hostnames from the default list + the optional per-instance list.
hosts=()
for f in "$conf" "$extra"; do
    [ -r "$f" ] || continue
    while IFS= read -r line; do
        line="${line%%#*}"                       # strip comments
        line="${line//[[:space:]]/}"             # strip whitespace
        [ -n "$line" ] || continue
        hosts+=("$line")
    done < "$f"
done

mkdir -p "$dropin_dir"

{
    echo "# Generated by vibeos-agent-egress.sh for instance '${instance}'."
    echo "# Do not edit — regenerated every start from the hostname allowlist."
    echo "[Service]"
    if [ "${#hosts[@]}" -eq 0 ]; then
        echo "# (no hostnames configured; egress stays deny-any except localhost)"
    fi
    for h in "${hosts[@]}"; do
        # getent ahosts yields both A and AAAA records; dedup per host.
        ips="$(getent ahosts "$h" 2>/dev/null | awk '{print $1}' | sort -u || true)"
        if [ -z "$ips" ]; then
            echo "# ${h}: unresolved at start — not allowed (fail-closed)"
            continue
        fi
        echo "# ${h}"
        while IFS= read -r ip; do
            [ -n "$ip" ] || continue
            echo "IPAddressAllow=${ip}"
        done <<< "$ips"
    done
} > "$out"

# Make systemd aware of the fresh /run drop-in before the agent unit starts.
systemctl daemon-reload

echo "egress allowlist compiled -> $out (${#hosts[@]} hostname(s))" >&2
